### PR TITLE
fix assets precompilation error with sprockets-rails 3

### PR DESCRIPTION
**Pull request by cheeseweasel**

### CODE REVIEW

**Comment by riseshia** [comment]
related #49
@seapy, could you check this PR? XD

**Comment by riseshia** [comment]
@cheeseweasel
Thanks to your pull request!
I apologize about long long time waiting for this.
I'm working on summernote 0.8.2 now, we could see this patch in the gem soon! XD
